# Generated by Django 4.0.5 on 2022-06-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
