# Generated by Django 4.0.5 on 2022-06-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_delete_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sauce',
            name='sauce',
        ),
        migrations.AddField(
            model_name='sauce',
            name='ChilliSauce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sauce',
            name='Ketchup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sauce',
            name='Mayonnaise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sauce',
            name='Mustard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sauce',
            name='PaprikaSauce',
            field=models.BooleanField(default=False),
        ),
    ]
